version: '3.6'

services:

  customerdb:
    image: postgres
    container_name: customerdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=customerdb